In [2]:
import numpy as np

## Data Types and Attributes

In [ ]:
# Numpy essentially has only one type of Data that is array - specifically nd-array

In [3]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [6]:
a2 = np.array([[1,2.0,3.3],
              [4,5,6.5]])

a3 = np.array([[[1,2,3],
               [4,5,6],
               [7,8,9]],
              [[10,11,12],
               [13,14,15],
              [16,17,18]]])

In [7]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [8]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [9]:
a1.shape

(3,)

In [10]:
a2.shape

(2, 3)

In [11]:
a3.shape

(2, 3, 3)

In [13]:
a1.ndim,a2.ndim,a3.ndim

(1, 2, 3)

In [15]:
a1.dtype,a2.dtype,a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [16]:
a1.size,a2.size,a3.size

(3, 6, 18)

In [17]:
type(a1),type(a2),type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [18]:
# Create a DataFrame from NumPy Array

In [19]:
import pandas as pd

In [20]:
df=pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## Creating Numpy arrays

In [21]:
sample_array = np.array([1,2,3])

In [22]:
sample_array

array([1, 2, 3])

In [23]:
ones = np.ones((2,3))

In [24]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [25]:
ones.dtype

dtype('float64')

In [26]:
type(ones)

numpy.ndarray

In [27]:
zeros = np.zeros((2,3))

In [28]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [29]:
range_array =np.arange(0,10,2)

In [30]:
range_array

array([0, 2, 4, 6, 8])

In [33]:
random_array = np.random.randint(0,10,size=(3,5))

In [34]:
random_array

array([[5, 5, 6, 0, 0],
       [5, 1, 2, 4, 7],
       [2, 7, 1, 3, 8]])

In [35]:
random_array.size

15

In [36]:
random_array.shape

(3, 5)

In [37]:
random_array_2=np.random.random((5,3))

In [38]:
random_array_2

array([[0.35852444, 0.37379115, 0.56280252],
       [0.65448462, 0.35097663, 0.98182116],
       [0.79738882, 0.17962629, 0.44279165],
       [0.95900944, 0.90831804, 0.60624015],
       [0.11634488, 0.13285607, 0.95937776]])

In [39]:
random_array_2.size

15

In [40]:
random_array_2.shape

(5, 3)

In [41]:
random_array_3 = np.random.rand(5,3)
random_array_3

array([[0.54769123, 0.91952822, 0.9247837 ],
       [0.21947821, 0.87829562, 0.38460733],
       [0.17978891, 0.4802715 , 0.60813943],
       [0.69700055, 0.13412854, 0.39246267],
       [0.56983518, 0.74681566, 0.22392322]])

In [42]:
## Pseudo Random Numbers
##np.random.seed()

In [44]:
np.random.seed(0)
random_array_4 =np.random.randint(10,size=(5,3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [48]:
np.random.seed(7)
random_array_5 = np.random.random((5,3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [49]:
random_array_5 = np.random.random((5,3))
random_array_5

array([[0.90959353, 0.21338535, 0.45212396],
       [0.93120602, 0.02489923, 0.60054892],
       [0.9501295 , 0.23030288, 0.54848992],
       [0.90912837, 0.13316945, 0.52341258],
       [0.75040986, 0.66901324, 0.46775286]])

## 3 Viewing arrays and matrices

In [50]:
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
a1

array([1, 2, 3])

In [52]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [53]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [55]:
a1[0]

1

In [56]:
a2[0]

array([1. , 2. , 3.3])

In [57]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [58]:
a3[:2,:2,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [60]:
a4 = np.random.randint(10,size=(2,3,4,5))
a4

array([[[[6, 7, 7, 9, 3],
         [0, 7, 7, 7, 0],
         [5, 4, 3, 1, 3],
         [1, 3, 4, 3, 1]],

        [[9, 5, 9, 1, 2],
         [3, 2, 2, 5, 7],
         [3, 0, 9, 9, 3],
         [4, 5, 3, 0, 4]],

        [[8, 6, 7, 2, 7],
         [3, 8, 6, 6, 5],
         [6, 5, 7, 1, 5],
         [4, 4, 9, 9, 0]]],


       [[[6, 2, 6, 8, 2],
         [4, 1, 6, 1, 5],
         [1, 6, 9, 8, 6],
         [5, 9, 7, 5, 4]],

        [[9, 6, 8, 1, 5],
         [5, 8, 3, 7, 7],
         [9, 4, 7, 5, 9],
         [6, 2, 0, 5, 3]],

        [[0, 5, 7, 1, 8],
         [4, 9, 0, 2, 0],
         [7, 6, 2, 9, 9],
         [5, 1, 0, 0, 9]]]])

In [61]:
a4[:,:,:,:2]

array([[[[6, 7],
         [0, 7],
         [5, 4],
         [1, 3]],

        [[9, 5],
         [3, 2],
         [3, 0],
         [4, 5]],

        [[8, 6],
         [3, 8],
         [6, 5],
         [4, 4]]],


       [[[6, 2],
         [4, 1],
         [1, 6],
         [5, 9]],

        [[9, 6],
         [5, 8],
         [9, 4],
         [6, 2]],

        [[0, 5],
         [4, 9],
         [7, 6],
         [5, 1]]]])

In [70]:
a4[1:,2:,0:1,:]

array([[[[0, 5, 7, 1, 8]]]])

## Manipulating and comparing arrays

In [71]:
a1

array([1, 2, 3])

In [72]:
ones=np.ones(3)
ones

array([1., 1., 1.])

In [73]:
a1+ones

array([2., 3., 4.])

In [74]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [75]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [76]:
a1/ones


array([1., 2., 3.])

In [77]:
a2**2

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

## Aggregation
aggregation = performing the same operation on a number of things

In [78]:
listy_list = [1,2,3]
type(listy_list
    )

list

In [79]:
sum(listy_list)

6

In [80]:
a1


array([1, 2, 3])

In [81]:
sum(listy_list)

6

In [82]:
sum(a1)

6

In [83]:
# Use Python's methods on Python datatypes
# And use NumPy's method on NUmPy arrays (np.sum())

In [84]:
# create a massaive NumPy array
massive_array = np.random.random(100000)
massive_array.size

100000

In [85]:
massive_array[:10]

array([0.62342345, 0.62955693, 0.9099729 , 0.96251949, 0.5850998 ,
       0.16489774, 0.39159332, 0.94455493, 0.34339118, 0.70507037])

In [86]:
%timeit sum(massive_array)# python sum
%timeit np.sum(massive_array) #NumPy's sum

13.1 ms ± 1.09 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)
46.1 µs ± 2.5 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [87]:
np.mean(a2)

3.6333333333333333

In [88]:
np.max(a2)

6.5

In [89]:
np.min(a2)

1.0

In [90]:
np.std(a2)

1.8226964152656422

In [91]:
np.var(a2)

3.3222222222222224

## Reshaping and transposing

In [92]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [93]:
a2.shape

(2, 3)

In [94]:
a2*a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [95]:
a2.reshape(2,3,1)

array([[[1. ],
        [2. ],
        [3.3]],

       [[4. ],
        [5. ],
        [6.5]]])

In [96]:
a2.shape

(2, 3)

In [97]:
a2.reshape(2,3,1).shape

(2, 3, 1)

In [98]:
a2_reshape = a2.reshape(2,3,1)

In [99]:
a2_reshape*a3

array([[[  1. ,   2. ,   3. ],
        [  8. ,  10. ,  12. ],
        [ 23.1,  26.4,  29.7]],

       [[ 40. ,  44. ,  48. ],
        [ 65. ,  70. ,  75. ],
        [104. , 110.5, 117. ]]])

In [101]:
#Transpose
a2.T

array([[1. , 4. ],
       [2. , 5. ],
       [3.3, 6.5]])

## Dot Product

In [102]:
np.random.seed(0)
mat1=np.random.randint(10,size=(5,3))
mat2=np.random.randint(10,size=(5,3))
mat1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [103]:
mat2

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]])

In [104]:
# Elementwise multiplication also known as Hadamard product
mat1*mat2

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]])

In [105]:
# Dot Product
np.dot(mat1,(mat2.T))

array([[ 51,  55,  72,  20,  15],
       [130,  76, 164,  33,  44],
       [ 67,  39,  85,  27,  34],
       [115,  69, 146,  37,  47],
       [111,  77, 145,  56,  64]])

## Dot Product Examples of sales

In [108]:
np.random.seed(0)
#number of jars sold
sales_amounts = np.random.randint(20,size=(5,3))
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [110]:
# Create weekly sales data frame
weekly_sales = pd.DataFrame(sales_amounts,
                           index=["Mon","Tues","Wed","Thurs","Fri"],
                          columns=["Alomd","Peanut","Cashew"])
weekly_sales

Alomd  Peanut  Cashew
Mon       12      15       0
Tues       3       3       7
Wed        9      19      18
Thurs      4       6      12
Fri        1       6       7

In [112]:
#Create the prices array
prices = np.array([10,8,12])
prices

array([10,  8, 12])

In [113]:
butter_prices =pd.DataFrame(prices.reshape(1,3),
                           index=["Price"],
                            columns=["Alomd","Peanut","Cashew"])
butter_prices

Alomd  Peanut  Cashew
Price     10       8      12

In [114]:
np.dot(weekly_sales,butter_prices)

ValueError: shapes (5,3) and (1,3) not aligned: 3 (dim 1) != 1 (dim 0)

In [115]:
np.dot(weekly_sales,butter_prices.T)

array([[240],
       [138],
       [458],
       [232],
       [142]])

In [116]:
weekly_sales["Total"] =np.dot(weekly_sales,butter_prices.T)

In [117]:
weekly_sales

Alomd  Peanut  Cashew  Total
Mon       12      15       0    240
Tues       3       3       7    138
Wed        9      19      18    458
Thurs      4       6      12    232
Fri        1       6       7    142

### Comparison Operators 

In [118]:
a1

array([1, 2, 3])

In [119]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [120]:
a1==a1

array([ True,  True,  True])

In [121]:
a1==a2

array([[ True,  True, False],
       [False, False, False]])

## Sorting Arrays

In [122]:
random_array = np.random.randint(10,size=(3,5))
random_array

array([[7, 8, 1, 5, 9],
       [8, 9, 4, 3, 0],
       [3, 5, 0, 2, 3]])

In [123]:
np.sort(random_array)

array([[1, 5, 7, 8, 9],
       [0, 3, 4, 8, 9],
       [0, 2, 3, 3, 5]])

In [124]:
np.argsort(random_array)

array([[2, 3, 0, 1, 4],
       [4, 3, 2, 0, 1],
       [2, 3, 0, 4, 1]], dtype=int64)

In [125]:
a1

array([1, 2, 3])

In [126]:
np.argsort(a1)

array([0, 1, 2], dtype=int64)

In [ ]:
## Converting the image into a array

## Picture of a panda

![title](panda.png)

In [135]:
# Turn the image into NumPy array
from matplotlib.image import imread
panda = imread("images/panda.png")
print(type(panda))

<class 'numpy.ndarray'>


In [136]:
panda

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       ...,

       [[0.13333334, 0.07450981, 0.05490196],
        [0.12156863, 0.0627451 , 0.04313726],
        [0.10980392, 0

In [137]:
panda.size,panda.shape,panda.ndim

(24465000, (2330, 3500, 3), 3)

In [139]:
panda[:2]

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]]], dtype=float32)

< img src="images/car-photo.png"/>